import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/provider";
// import { ToastProvider } from "react-toast-notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ToastProvider> */}
        <Providers>{children}</Providers>
        {/* </ToastProvider> */}
      </body>
    </html>
  );
}
